// Entry generator for the Useful Mods List
// Pulls from modpack-dev-wiki/scripts/useful_mods.json
// Not ran on site build, ran manually through VSCode terminal or NodeJS
// npm run generate:usefulmods

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { parseArgs } from 'node:util';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DATA_PATH = path.join(__dirname, "useful_mods.json");
const OUTPUT_DIR = path.join(path.join(__dirname, '..'), "src/routes/wiki/useful-mods");

const DESIRED_LOADERS = ["fabric", "forge", "neoforge"];
const DESIRED_VERSIONS = ["1.19.2", "1.20.1", "1.21.1", "26.1"];

const data = JSON.parse(fs.readFileSync(DATA_PATH, "utf-8"));
const mods = data.mods;

function formatLinks(link) {
  return [
    link?.curseforge ? `[CF](${link.curseforge})` : "",
    link?.modrinth ? `[MR](${link.modrinth})` : ""
  ].filter(Boolean).join(" / ");
}

function formatLoader(loader) {
  switch (loader) {
    case "forge": return "Forge";
    case "neoforge": return "NeoForge";
    case "fabric": return "Fabric";
  }
  return `BAD LOADER!! ${loader} DOESN'T EXIST!!`
}

function formatCategory(category) {
  switch (category) {
    case "performance": return "Performance";
    case "bug_fixes": return "Bug Fixes";
    case "profiling": return "Profiling/Debugging";
    case "documentation": return "Documentation";
    case "multiplayer": return "Free Multiplayer"
    case "utility": return "Utility"
  }
  return `BAD CATEGORY!! ${category} DOESN'T EXIST!!`
}

function getTableDescriptor(category) {
  switch (category) {
    case "performance": return "These mods directly improve modpack performance through code optimizations.";
    case "bug_fixes": return "These mods fix bugs present in Vanilla Minecraft, other mods, or in loaders.";
    case "profiling": return "These mods help profile and diagnose issues for modpacks, so that issues can be found and fixed.";
    case "documentation": return "These mods help provide information to the player and guide them through content in the modpack.";
    case "multiplayer": return "These mods allow for free multiplayer without the cost or hassle of setting up a server."
    case "utility": return "These are mods that are essential for creating, removing, and editing aspects of the game to create custom content and unique experiences for a modpack."
  }
  return `BAD CATEGORY!! ${category} DOESN'T EXIST!!`
}

function getFrontMatter(key) {
  let splitKey = key.split("/")
  let category = splitKey[0];
  let version = splitKey[1];
  let loader = formatLoader(splitKey[2]);
  return `---
title: ${formatCategory(category)} mods for ${loader} ${version}
tags: mods, ${loader}, ${version}
description: ${formatCategory(category)} mods for ${loader} ${version}
---

<script lang="ts">
import { Discord } from '$lib/reusables';
</script>

<!-- 
DO NOT EDIT THIS FILE MANUALLY!! Mod entries and page information are handled through these files, respectively:
https://github.com/Modpack-Dev-Knowledgebase/modpack-dev-wiki/blob/main/scripts/useful_mods.json
https://github.com/Modpack-Dev-Knowledgebase/modpack-dev-wiki/blob/main/scripts/usefulMods.js

Manual edits to this file will be overritten on next script run.
-->

# ${formatCategory(category)} mods for ${loader} ${version}

${getTableDescriptor(category)}\n\n
`
}

function writeFile(newPath, contents, cb) {
  fs.mkdir(path.dirname(newPath), { recursive: true }, function (err) {
    if (err) return cb(err);

    fs.writeFile(newPath, contents, cb);
  });
}

function buildTable(modList) {
  const sorted = [...modList].sort((a, b) =>
    a.display_name.localeCompare(b.display_name)
  );

  const header =
    `| Name | Links | Description | Alternatives |
|------|-------|-------------| --------------|`;

  const rows = sorted.map(mod =>
    `| ${mod.display_name} | ${formatLinks(mod.link)} | ${mod.description} | ${mod.alternatives || "-"} |`
  ).join("\n");

  return `${header}\n${rows}`;
}

async function getVersionInfoFromModrinth(url) {
  const mrUrl = new URL(url);
  const slug = mrUrl.pathname.split('/').filter(Boolean).pop();

  let out = null;
  try {
    const response = await fetch(`https://api.modrinth.com/v2/project/${encodeURIComponent(slug)}`);
    if (!response.ok) {
      throw new Error(`Response status: ${response.status}`);
    }

    const result = await response.json();
    if (result.game_versions != null && result.loaders != null) {
      out = {
        loaders: result.loaders,
        versions: result.game_versions
      };
    }
  } catch (error) {
    console.log(`Failed to get info from Modrinth for url: ${url}\n\terror: ${error.message}`);
  }

  return out;
}

// Used to lookup the modloadertype number for curseforge: https://docs.curseforge.com/rest-api/?javascript#tocS_ModLoaderType
const LOADER_CURSEFORGE_TYPE_MAP = ["any", "forge", "cauldron", "liteloader", "fabric", "quilt", "neoforge"];
let CF_API_KEY = "";

async function getVersionInfoFromCurseforge(url) {
  const cfUrl = new URL(url);
  const slug = cfUrl.pathname.split('/').filter(Boolean).pop();

  let out = null;
  try {
    // For Curseforge we must search for the mod via slug to get it's Id to use to get version/loader info.
    const response = await fetch(`https://api.curseforge.com/v1/mods/search?gameId=432&slug=${encodeURIComponent(slug)}`, {
      method: "GET",
      headers: {
        'Accept':'application/json',
        'x-api-key':CF_API_KEY
      }
    });

    if (!response.ok) {
      throw new Error(`Response status: ${response.status}`);
    }

    const result = await response.json();
    const mod = result.data?.find(m => m.slug === slug);

    if (mod == null) {
      throw new Error(`Could not find mod with slug: ${slug}`);
    }

    // Afterwards it's easiest to search for a file of a certain version/loader to confirm the mod supports it.
    let versionsToSearch = [...DESIRED_VERSIONS];
    let loadersToSearch = [...DESIRED_LOADERS];

    let versionsFound = new Set();
    let loadersFound = new Set();

    while (versionsToSearch.length != 0) {
      const version = versionsToSearch.pop();
      const response = await fetch(`https://api.curseforge.com/v1/mods/${mod.id}/files?gameVersion=${version}`, {
        method: "GET",
        headers: {
          'Accept':'application/json',
          'x-api-key':CF_API_KEY
        }
      });

      if (!response.ok) {
        throw new Error(`Response status: ${response.status}`);
      }

      const result = await response.json();
      if (result.data.length > 0) {
        versionsFound.add(version);
      }
    }

    while (loadersToSearch.length != 0) {
      const loader = loadersToSearch.pop();
      const loaderTypeNum = LOADER_CURSEFORGE_TYPE_MAP.indexOf(loader);
      const response = await fetch(`https://api.curseforge.com/v1/mods/${mod.id}/files?modLoaderType=${loaderTypeNum}`, {
        method: "GET",
        headers: {
          'Accept':'application/json',
          'x-api-key':CF_API_KEY
        }
      });

      if (!response.ok) {
        throw new Error(`Response status: ${response.status}`);
      }

      const result = await response.json();
      if (result.data.length > 0) {
        loadersFound.add(loader);
      }
    }

    out = {
      loaders: [...loadersFound],
      versions: [...versionsFound]
    };
  } catch (error) {
    console.log(`Failed to get info from Curseforge for url: ${url}\n\terror: ${error.message}`);
  }

  return out;
}

async function updateModVersion(mod) {
  // always try hitting modrinth first even if we don't have a link and need to guess the slug via a curseforge link
  const mrUrl = mod.link.modrinth ? mod.link.modrinth : mod.link.curseforge;
  let info = await getVersionInfoFromModrinth(mrUrl);
  if (info == null && CF_API_KEY != "") {
    console.log(`\tModrinth failed trying Curseforge instead... ${mod.link.curseforge}`)
    info = await getVersionInfoFromCurseforge(mod.link.curseforge);
  }

  if (info != null) {
    mod.versions = [...new Set([...mod.versions, ...info.versions])].sort().filter(v => DESIRED_VERSIONS.includes(v));
    mod.loaders = [...new Set([...mod.loaders, ...info.loaders])].sort().filter(v => DESIRED_LOADERS.includes(v));
  }
}

///////////////////
// PROCESS START //
///////////////////

// Cmd line options
const options = {
  // dry run option
  dryrun: {
    type: 'boolean',
    short: 'd',
  },
  // pings modrinth and/or curseforge to confirm and write back supported versions/loaders for each mod
  updateversions: { 
    type: 'boolean',
    short: 'u',
  },
  // provide curseforge API key to be able to ping their servers for info
  curseforgekey: {
    type: 'string',
    short: 'c',
  },
};

// Parse additional args
let args;
try {
  ({ values: args } = parseArgs({ 
    args: process.argv.slice(2), 
    options 
  }));
} catch (err) {
  console.error('Argument Error:', err.message);
  process.exit(1);
}

if (args.curseforgekey) {
  CF_API_KEY = args.curseforgekey;
} else if (args.updateversions) {
  console.log(`No Curseforge API key provided, will only check using Modrinth`);
}

const grouped = {};

for (const mod of mods) {
  if (args.updateversions) {
    await updateModVersion(mod);
  }
  for (const category of mod.categories) {
    for (const version of mod.versions) {
      for (const loader of mod.loaders) {
        const key = `${category}/${version}/${loader}`;
        if (!grouped[key]) grouped[key] = [];
        grouped[key].push(mod);
      }
    }
  }
}

// Write back to useful_mods.json
if (!args.dryrun && args.updateversions) {
  fs.writeFileSync(DATA_PATH, JSON.stringify(data, null, "    "), "utf-8");
}

console.log("Grouped keys:", Object.keys(grouped));
if (args.dryrun) {
  process.exit(0);
}

const footer = `\n\n\\* - A must-have mod for nearly any modpack. Only in very rare circumstances should you not use this mod or an equivalent.

\** - Prone to issues or conflicts with other mods`
for (const key in grouped) {
  const filePath = path.join(OUTPUT_DIR, key, "+page.svx");

  // if (!fs.existsSync(filePath)) {
  //   console.warn(`Missing file: ${filePath}`);
  //   continue;
  // }
  grouped[key].sort((a, b) =>
    a.display_name.localeCompare(b.display_name)
  );
  const table = buildTable(grouped[key]);

  const finalContent = getFrontMatter(key) + table + footer

  // console.log(updated)
  try {

    writeFile(filePath, finalContent, e => console.log(`Updated: ${filePath}`));
  } catch (err) {
    console.error('Update failed:', err.message);
  }
}
